# -*- coding: utf-8 -*-
"""AC 1 - Analise Exploratoria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmapjkiKpqoDPMN7RN-RcpcX0IP_czvN
"""

import pandas as pd
import numpy as np

df = pd.read_csv("./arquivo_final.csv", sep=",")

# Convert the DATE_SALE column to datetime format
df['DATE_BUILD'] = pd.to_datetime(df['DATE_BUILD'], format='%d-%m-%Y')


# Create 5 bins for the date range
date_bins = pd.date_range(start=df['DATE_BUILD'].min(), end=df['DATE_BUILD'].max(), periods=5)

# Create a new column to specify which bin/date range each sale date belongs to
df['DATE_BIN'] = pd.cut(df['DATE_BUILD'], bins=date_bins)

# Use groupby to aggregate data based on these bins
aggregated_data = df.groupby('DATE_BIN').agg(
    Vendas=('SALES_PRICE', 'count'),
    Média_de_Venda=('SALES_PRICE', 'mean'),
    Desvio_Padrão=('SALES_PRICE', 'std')
).reset_index()

# Round the Média_de_Venda to two decimal places
aggregated_data['Média_de_Venda'] = aggregated_data['Média_de_Venda'].round(2)

# Calculate Coeficiente de Variação = (Standard Deviation / Mean) * 100
aggregated_data['Coeficiente de Variação'] = (aggregated_data['Desvio_Padrão'] / aggregated_data['Média_de_Venda']) * 100

# Round the Coeficiente de Variação to two decimal places
aggregated_data['Coeficiente de Variação'] = aggregated_data['Coeficiente de Variação'].round(2)

aggregated_data['Desvio_Padrão'] =aggregated_data['Desvio_Padrão'].round(2)

# Rename columns for clarity
aggregated_data.rename(columns={'DATE_BIN': 'Intervalo de Data'}, inplace=True)

# Save the resulting dataframe to a CSV file
aggregated_data.to_csv("dados_agregados.csv", index=False, sep=",")

print("File saved successfully!")